ARG DOCKER_REPO
ARG ROS_DISTRO
ARG IMAGE_SUFFIX
FROM $DOCKER_REPO:$ROS_DISTRO$IMAGE_SUFFIX
ARG USERNAME
ARG USER_UID=1000
ARG USER_GID=$USER_UID

# Create the user
RUN groupadd --gid $USER_GID $USERNAME \
    && useradd --uid $USER_UID --gid $USER_GID -m $USERNAME \
    && apt-get update \
    && apt-get install -y sudo \
    && echo $USERNAME ALL=\(root\) NOPASSWD:ALL > /etc/sudoers.d/$USERNAME \
    && chmod 0440 /etc/sudoers.d/$USERNAME

# Install additional packages
RUN apt-get update && apt-get upgrade -y && apt-get install -y \
    python3-pip \
    python-is-python3 \
    ssh \
    neovim \
    git \
    nano \
    build-essential \
    cmake \
    unzip \
    wget \
    curl \
    virtualenvwrapper \
    ros-$ROS_DISTRO-ackermann-msgs \
    ros-$ROS_DISTRO-urg-node \
    ros-$ROS_DISTRO-joy \
    ros-$ROS_DISTRO-teleop-tools \
    ros-$ROS_DISTRO-serial-driver \
    ros-$ROS_DISTRO-joint-state-publisher \
    ros-$ROS_DISTRO-nav2-lifecycle-manager \
    ros-$ROS_DISTRO-nav2-map-server \
    ros-$ROS_DISTRO-nav2-amcl \
    ros-$ROS_DISTRO-robot-localization \
    ros-$ROS_DISTRO-tf-transformations \
    ros-$ROS_DISTRO-asio-cmake-module \
    ros-$ROS_DISTRO-odom-to-tf-ros2 \
    ros-$ROS_DISTRO-joy-linux \
    libssl-dev \
    libusb-1.0-0-dev \
    libudev-dev \
    pkg-config \
    libgtk-3-dev \
    libglfw3-dev \
    libglu1-mesa-dev

# Install Python packages
RUN pip install --no-cache-dir --upgrade pip && \
    pip install --no-cache-dir --ignore-installed numpy pandas "transforms3d==0.4.2" opencv-python

# Clone and build the librealsense SDK from source
RUN git clone https://github.com/IntelRealSense/librealsense.git --branch v2.50.0 && \
    mkdir -p librealsense/build && \
    cd librealsense/build && \
    cmake ../ -DCMAKE_BUILD_TYPE=Release -DFORCE_LIBUVC=ON -DBUILD_EXAMPLES=OFF -DBUILD_WITH_CUDA=OFF && \
    make -j$(nproc) && \
    sudo make install

# Clone the RealSense ROS2 wrapper package and build
RUN git clone https://github.com/IntelRealSense/realsense-ros.git src/realsense2_camera --branch ros2 && \
    cd src/realsense2_camera && \
    colcon build

# Set the default user
USER $USERNAME
ENV SHELL=/bin/bash
SHELL ["/bin/bash", "-c"]

# Add .local/bin to PATH
RUN echo "export PATH=/home/$USERNAME/.local/bin${PATH:+:${PATH}}" >> /home/$USERNAME/.bashrc

# Source ROS environment automatically
RUN echo "source /opt/ros/$ROS_DISTRO/setup.bash" >> /home/$USERNAME/.bashrc && \
    echo "source /home/ss24_racing1/install/setup.bash" >> /home/$USERNAME/.bashrc && \
    echo "source /usr/share/virtualenvwrapper/virtualenvwrapper.sh" >> /home/$USERNAME/.bashrc

# Set the default command
CMD ["/bin/bash"]
