/**:
 ros__parameters:
    map_name: HRL
    namespace: /planner
    goal_topic: /goal
    centerline_topic: /centerline
    odom_topic: /odom
    pose_topic: /amcl_pose 
    drive_topic: /drive
    base_frame: base_link
    map_frame: map

# centerline_publisher:
#   ros__parameters:
    
goal_publisher:
  ros__parameters:
    min_goal_distance: 1.0
    use_slam_pose: True
    waypoints_mode: centerline
    waypoints_step_size: 5 # TODO: REMOVE
    publish_drive: True
    steering_pid_kp: 0.1 #0.5
    steering_pid_ki: 0.0 #0.0
    steering_pid_kd: 0.0 #0.1
    drive_speed: 4.0
