/**:
 ros__parameters:
    map_name: Spielberg
    namespace: planner
    
centerline_publisher:
  ros__parameters:
    topic: '/centerline'

waypoint_follower:
  ros__parameters:
    topic: '/waypoint'
    mode: 'centerline'
    odom_topic: /racecar/odom
    pose_topic: /racecar/pose
